export const filters = ['all', 'construction', 'renovation', 'landscape', 'architecture']

export const allProjects = [
  {
    name: 'project1',
    title: 'home.project1.title',
    shortDescription: 'home.project1.shortDescription',
    description: 'home.project1.description',
    location: 'Wemmel, Brussels',
    area: '200m2',
    status: 'In progress',
    defaultImage: '/images/project/project1.png',
    link: '/projects/project1',
    images: [
      '/images/project/project1.png',
      '/images/project/project2.png',
      '/images/project/project3.png',
      '/images/project/project4.png',
      '/images/project/project5.png',
    ],
    beforeImages: [
      '/images/project/project1.png',
      '/images/project/project2.png',
      '/images/project/project3.png',
      '/images/project/project4.png',
      '/images/project/project5.png',
    ],
    afterImages: [
      '/images/project/project1.png',
      '/images/project/project2.png',
      '/images/project/project3.png',
      '/images/project/project4.png',
      '/images/project/project5.png',
    ],
    plansImages: [
      '/images/project/project2.png',
      '/images/project/project3.png',
      '/images/project/project4.png',
      '/images/project/project5.png',
      '/images/project/project3.png',
    ],
    filter: ['all', 'construction', 'architecture'],
  },
  {
    name: 'project2',
    title: 'home.project2.title',
    shortDescription: 'home.project2.shortDescription',
    description: 'home.project2.description',
    location: 'Wemmel, Brussels',
    area: '200m2',
    status: 'In progress',
    defaultImage: '/images/project/project1.png',
    link: '/projects/project2',
    images: ['/images/project/project1.png', '/images/project/project1.png'],
    beforeImages: ['/images/project/project1.png', '/images/project/project1.png'],
    afterImages: ['/images/project/project1.png', '/images/project/project1.png'],
    plansImages: ['/images/project/project1.png', '/images/project/project1.png'],
    filter: ['all', 'construction'],
  },
  {
    name: 'project3',
    title: 'home.project3.title',
    shortDescription: 'home.project3.shortDescription',
    description: 'home.project3.description',
    location: 'Wemmel, Brussels',
    area: '200m2',
    status: 'In progress',
    defaultImage: '/images/project/project1.png',
    link: '/projects/project3',
    images: ['/images/project/project1.png', '/images/project/project1.png'],
    beforeImages: ['/images/project/project1.png', '/images/project/project1.png'],
    afterImages: ['/images/project/project1.png', '/images/project/project1.png'],
    plansImages: ['/images/project/project1.png', '/images/project/project1.png'],
    filter: ['all', 'construction'],
  },
  {
    name: 'project4',
    title: 'home.project4.title',
    description: 'home.project4.description',
    filter: ['all', 'construction'],
  },
  {
    name: 'project5',
    title: 'home.project5.title',
    description: 'home.project5.description',
    filter: ['all', 'renovation'],
  },
  {
    name: 'project6',
    title: 'home.project6.title',
    description: 'home.project6.description',
    filter: ['all', 'renovation'],
  },
  {
    name: 'project7',
    title: 'home.project7.title',
    description: 'home.project7.description',
    filter: ['all', 'renovation'],
  },
  {
    name: 'project8',
    title: 'home.project8.title',
    description: 'home.project8.description',
    filter: ['all'],
  },
  {
    name: 'project9',
    title: 'home.project9.title',
    description: 'home.project9.description',
    filter: ['all', 'landscape'],
  },
  {
    name: 'project10',
    title: 'home.project10.title',
    description: 'home.project10.description',
    filter: ['all', 'landscape'],
  },
  {
    name: 'project11',
    title: 'home.project11.title',
    description: 'home.project11.description',
    filter: ['all'],
  },
  {
    name: 'project12',
    title: 'home.project12.title',
    description: 'home.project12.description',
    filter: ['all'],
  },
]
